import UtilityBar from "@/components/UtilityBar";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - RamSoft",
  description:
    "RamSoft is committed to protecting your privacy. Read our privacy policy to learn how we collect, use, and protect your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <UtilityBar />
      <Nav />
      <main>
        {/* Hero Banner */}
        <section className="bg-dodger py-16 lg:py-24">
          <div className="mx-auto max-w-[1200px] px-6">
            <p className="font-[family-name:var(--font-manrope)] text-spring font-bold text-[11px] uppercase tracking-[2px] mb-4">
              Legal
            </p>
            <h1 className="font-[family-name:var(--font-hanken)] font-extrabold text-[36px] lg:text-[56px] text-white leading-tight">
              Privacy Policy
            </h1>
            <p className="font-[family-name:var(--font-manrope)] text-white/70 text-base lg:text-lg mt-4">
              Last updated: April 1, 2026
            </p>
          </div>
        </section>

        {/* Content */}
        <section className="py-14 lg:py-20">
          <div className="mx-auto max-w-[860px] px-6 privacy-prose">
            <p>
              RamSoft is committed to protecting your privacy. This privacy
              policy describes our collection, use, and disclosure of your
              personal information when you utilize RamSoft offerings and
              products. By using RamSoft Services, you agree to the collection
              and use of information in accordance with this Privacy Policy.
            </p>
            <p className="font-semibold text-navy-mid">
              Please read this privacy policy in full. If you do not agree to
              the terms below then please do not use this site or services.
            </p>

            {/* Definitions */}
            <h2>Definitions</h2>
            <p>For the purposes of this Privacy Policy:</p>
            <p>
              <strong>You</strong> means the individual or entity accessing or
              using the Service, whether in their own representative capacity
              or on behalf of another.
            </p>
            <p>
              <strong>Company</strong> (referred to as either &quot;the
              Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
              in this Privacy Policy) refers to RamSoft Inc., and its
              subsidiaries, alliances and affiliates.
            </p>
            <ul>
              <li>
                <strong>Affiliate</strong> means any entity, subsidiaries,
                joint venture partners, or other companies under the control
                of RamSoft, Inc.
              </li>
              <li>
                <strong>Account</strong> means a unique account created for
                you to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Service</strong> refers to any RamSoft offering or
                product.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural person or
                legal entity who processes the data on behalf of the Company.
              </li>
              <li>
                <strong>Third-party social media service</strong> refers to
                any website or social network website through which a User can
                log in or create an account to use the Service.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on
                your computer, mobile device, or any other device by a
                website, containing the details of your browsing history on
                that website among its many uses.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself.
              </li>
              <li>
                <strong>Website</strong> refers to any publicly available
                online RamSoft offering including, but not limited to, the
                RamSoft Site at{" "}
                <strong>ramsoft.com</strong>, OmegaAI&reg; at{" "}
                <strong>omegaai.com</strong>, Blume&reg; at{" "}
                <strong>blume.omegaai.com</strong> and RamSoft Communities at{" "}
                <strong>support.ramsoft.com</strong>.
              </li>
            </ul>

            {/* Collecting and Using Your Personal Data */}
            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Personal Data</h3>
            <p>
              While using our Service, we may ask you to provide us with
              certain personally identifiable information that can be used to
              contact or identify you. Personally identifiable information may
              include, but is not limited to: Email address, First name and
              last name, Phone number, Mailing Address including State,
              Province, ZIP/Postal code, City.
            </p>
            <h3>Usage Data</h3>
            <p>
              Usage Data may be collected automatically when using the
              Service. Usage Data may include but is not limited to
              information such as your device type, browser type, the pages of
              our Service that you visit, the time and date of your visit, the
              time spent on those pages and unique device identifiers.
            </p>
            <h3>Tracking Technologies and Cookies</h3>
            <p>
              We use Cookies and other similar tracking technologies to track
              your activity on our Service and store certain information. You
              can instruct your browser to limit the types of Cookies used
              while using our Service. However, if you do not accept Cookies,
              you may not be able to use some parts of our Service. For more
              information about the cookies we use and your choices regarding
              cookies, please refer to our Cookies policy.
            </p>

            {/* Use of Your Personal Data */}
            <h2>Use of Your Personal Data</h2>
            <p>
              The Company may use Personal Data for the following purposes:
            </p>
            <ul>
              <li>
                <strong>To provide and maintain our Service.</strong>
              </li>
              <li>
                <strong>For the performance of a contract,</strong> including
                the development, compliance and undertaking of the purchase
                contract for the products, items or services you have
                purchased or of any other contract with us through the
                Service.
              </li>
              <li>
                <strong>To contact you,</strong> including by email, telephone
                calls, SMS, or other equivalent forms of electronic
                communication regarding updates or informative communications
                related to the functionalities, products, or contracted
                services.
              </li>
              <li>
                <strong>To provide you</strong> with news, special offers and
                general information about other goods, services and events
                which we offer that are similar to those that you have already
                purchased or enquired about unless you have opted not to
                receive such information.
              </li>
              <li>
                <strong>To manage your requests:</strong> To attend to and
                manage your requests to us.
              </li>
            </ul>
            <p>
              We may share your personal information in the following
              situations:
            </p>
            <ul>
              <li>
                <strong>With Service Providers:</strong> We may share your
                personal information with Service Providers to monitor and
                analyze your use of our Service, to contact you, or for
                payment processing.
              </li>
              <li>
                <strong>With Affiliates:</strong> We may share your
                information with our Affiliates, in which case we will require
                those Affiliates to comply with this Privacy Policy.
              </li>
              <li>
                <strong>With Business partners:</strong> We may share your
                information with our business partners to offer you certain
                products, services, or promotions.
              </li>
            </ul>

            {/* Retention */}
            <h2>Retention of Your Personal Data</h2>
            <p>
              We will retain and use your Personal Data to the extent
              necessary to comply with our legal obligations or comply with
              applicable laws, resolve disputes, and enforce our agreements
              and policies. Usage Data is generally retained for a shorter
              period of time, except when this data is used to strengthen the
              security or to improve the functionality of our Service, or we
              are legally obligated to retain this data for longer time
              periods.
            </p>

            {/* Transfer */}
            <h2>Transfer of Your Personal Data</h2>
            <p>
              Your information, including Personal Data, is processed by the
              Company in any place where the parties involved in the
              processing are located. This means that your information may be
              transferred to — and maintained on — computers located outside
              of your state, province, country, or other governmental
              jurisdiction and subject to data protection laws that may differ
              from those in your jurisdiction.
            </p>
            <p>
              Your consent to this Privacy Policy followed by your submission
              of personal information represents your agreement to that
              transfer. The Company will take all steps reasonably necessary
              to ensure that your data is treated securely and in accordance
              with this Privacy Policy.
            </p>

            {/* Disclosure */}
            <h2>Disclosure of Your Personal Data</h2>
            <h3>Business Transactions</h3>
            <p>
              If the Company is involved in a merger, acquisition or asset
              sale, your Personal Data may be transferred and your data may
              become subject to a different Privacy Policy.
            </p>
            <h3>Law Enforcement</h3>
            <p>
              Under certain circumstances, the Company may be required to
              disclose your Personal Data, if required to do so by law or in
              response to valid requests by public authorities (e.g., a court
              or a government agency).
            </p>
            <h3>Other Legal Requirements</h3>
            <p>
              The Company may disclose your Personal Data based on the good
              faith belief that such action is necessary to comply with a
              legal obligation, protect and defend the rights or property of
              the Company, prevent or investigate possible wrongdoing in
              connection with the Service, protect the personal safety of
              users of the Service or the public and protect against legal
              liability.
            </p>

            {/* Security */}
            <h2>Security of Your Personal Data</h2>
            <p>
              The security of your Personal Data is important to us. No
              method of transmission over the Internet, or method of
              electronic storage is 100% secure. While we strive to use
              commercially acceptable means to protect your Personal Data, we
              cannot guarantee its absolute security from hackers and
              cyberattacks. The Company maintains suitable cyber insurance
              coverage to supplement the potential of such an event occurring.
            </p>

            {/* Breach Notification */}
            <h2>Breach Notification</h2>
            <p>
              In the event of a personal data breach that is likely to result
              in a risk to the rights and freedoms of individuals, the Company
              will notify the relevant supervisory authority without undue
              delay and, where feasible, within 72 hours of becoming aware of
              the breach, in accordance with applicable data protection laws.
              Where the breach is likely to result in a high risk to the
              rights and freedoms of individuals, the Company will also notify
              the affected individuals without undue delay.
            </p>

            {/* Deletion */}
            <h2>Deletion of Personal Data</h2>
            <p>
              Upon issuing written instructions to RamSoft to cease processing
              of Personal Data, whether due to withdrawal of consent,
              fulfillment of the specified purpose, or any other reason,
              RamSoft shall restrict further active processing of the relevant
              Personal Data.
            </p>
            <p>
              All users, regardless of region, can request the deletion of
              their Personal Data by contacting us at{" "}
              <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
              Upon receiving a valid request, we will take appropriate steps
              to delete the requested data unless legal or regulatory
              requirements mandate its retention.
            </p>

            {/* Children's Privacy */}
            <h2>Children&apos;s Privacy</h2>
            <p>
              Our services may involve the collection and processing of
              personal information relating to individuals who are below the
              age required to provide valid consent under applicable data
              protection laws. Where required by applicable law, we obtain
              verifiable consent from a parent or legal guardian prior to
              collecting or processing such personal information.
            </p>
            <p>
              If you are a parent or legal guardian and believe that personal
              information relating to a minor has been collected or processed
              without appropriate consent, please contact us at{" "}
              <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
            </p>

            {/* Additional Jurisdictions */}
            <h2>Additional Information for Certain Jurisdictions</h2>
            <p>
              Below provides additional information about the collection, use,
              and sharing of privacy data in various regions of the world.
              These separate provisions may be applicable to you based on the
              location of you or the data.
            </p>

            {/* CCPA */}
            <h2>I — California Consumer Privacy Act (CCPA)</h2>
            <p>
              In order to exercise any of your rights under the CCPA, and if
              you are a California resident, you may reach out using the
              information provided in the Contact Us section of this policy or
              by sending us an email at{" "}
              <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
            </p>
            <h3>Additional Consumer Rights Under the CCPA:</h3>
            <ul>
              <li>
                <strong>Right to Know / Access:</strong> You have the right to
                request that the Company disclose the categories and specific
                pieces of Personal Information we have collected about you.
              </li>
              <li>
                <strong>Right to Correction:</strong> You have the right to
                request the correction of inaccurate Personal Information that
                the Company maintains about you.
              </li>
              <li>
                <strong>Right to Non-Discrimination:</strong> The Company will
                not discriminate against you for exercising any of your rights
                under the CCPA.
              </li>
              <li>
                <strong>Do Not Sell My Information:</strong> Under the CCPA,
                California residents have the right to opt out of the sale of
                their personal information by emailing us at{" "}
                <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
              </li>
            </ul>

            {/* PIPEDA */}
            <h2>II — PIPEDA</h2>
            <p>
              We understand that you may have preferences about how your data
              is used. If you would like to review or request changes to any
              of your personally identifiable information that is collected by
              us, in relation to PIPEDA, please email us at{" "}
              <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
            </p>

            {/* DPDPA */}
            <h2>
              III — Digital Personal Data Protection Act (DPDPA) — India
            </h2>
            <p>
              If you are located in India, the processing of your personal
              data will be governed by the provisions of the Digital Personal
              Data Protection Act, 2023.
            </p>
            <p>
              As a Data Principal, you have the following rights under
              applicable law:
            </p>
            <ul>
              <li>
                <strong>Right to Access Information:</strong> You have the
                right to request confirmation as to whether your personal data
                is being processed and to obtain information regarding the
                categories of personal data being processed.
              </li>
              <li>
                <strong>Right to Withdraw Consent:</strong> Where personal
                data is processed based on your consent, you may withdraw such
                consent at any time.
              </li>
              <li>
                <strong>Right to Grievance Redressal:</strong> You have the
                right to raise grievances regarding the processing of your
                personal data.
              </li>
              <li>
                <strong>Right to Nominate:</strong> You have the right to
                nominate another individual who may exercise your rights in
                the event of your death or incapacity.
              </li>
            </ul>
            <p>
              <strong>Data Protection Officer Contact:</strong>{" "}
              <a href="mailto:dpo@ramsoft.com">dpo@ramsoft.com</a>
            </p>

            {/* GDPR */}
            <h2>IV — European Economic Area — GDPR</h2>

            <h3>1. Contact</h3>
            <p>
              <strong>Data Processor:</strong> RamSoft Inc., 8 King Street
              East, Toronto, ON, Canada.
            </p>
            <p>
              <strong>EU-GDPR Representative:</strong> AF Pharma Service
              Europe SL Muntaner 281, 08021 Barcelona, Spain.
            </p>
            <p>
              <strong>Data Protection Officer (DPO):</strong>{" "}
              <a href="mailto:dpo@ramsoft.com">dpo@ramsoft.com</a>
            </p>

            <h3>2. Scope of Data Protection</h3>
            <p>
              Data protection applies to personal data, i.e. all information
              relating to an identified or identifiable natural person. If you
              have any questions about this Privacy Policy, please contact us
              via e-mail:{" "}
              <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
            </p>

            <h3>3. Your Rights</h3>
            <ul>
              <li>
                <strong>Right to access</strong> — We will confirm whether we
                are processing any of your personal data, which data we are
                processing, and for what purpose.
              </li>
              <li>
                <strong>Right to rectification</strong> — If any of the data
                we have stored is incorrect, we would certainly be happy to
                correct it.
              </li>
              <li>
                <strong>Right to erasure</strong> — We will comply with your
                request as far as legally possible.
              </li>
              <li>
                <strong>Right to restriction of processing</strong> — Should
                you wish to restrict use, we will comply as far as legally
                possible.
              </li>
              <li>
                <strong>Right to withdraw your consent</strong> — Should you
                wish to revoke any previously granted consent, we will comply.
              </li>
              <li>
                <strong>Right to be informed</strong> — Individuals have the
                right to know how their data is collected, used, and
                processed.
              </li>
              <li>
                <strong>Right to data portability</strong> — Individuals can
                request that their data be transferred to another controller
                in a structured, commonly used, and machine-readable format.
              </li>
              <li>
                <strong>Right to object</strong> — Individuals can object to
                the processing of their personal data in certain
                circumstances, including direct marketing.
              </li>
            </ul>

            <h3>4. Retention Period</h3>
            <p>
              The data processed by us will be retained only for as long as
              necessary to fulfil the purposes for which it was collected, or
              as required by applicable law. Upon expiry of the applicable
              retention period, personal data will be securely deleted or
              anonymized.
            </p>

            <h3>5. SSL or TLS Encryption</h3>
            <p>
              For security reasons and to protect the transmission of
              confidential content, this site uses SSL or TLS encryption. You
              can recognize an encrypted connection by the fact that the
              address line of the browser changes from &quot;http://&quot; to
              &quot;https://&quot; and by the lock symbol in your browser
              line.
            </p>

            <h3>6. Children</h3>
            <p>
              Our services may involve the collection and processing of
              personal information relating to individuals who are below the
              age required to provide valid consent under applicable data
              protection laws. Where required by applicable law, we obtain
              verifiable consent from a parent or legal guardian prior to
              collecting or processing such personal information.
            </p>

            <h3>7. Transfer</h3>
            <p>
              The Company may only transfer personal data from within the
              EU/EEA to entities located outside of this region under specific
              conditions, including where the third country provides an
              equivalent level of data protection, under EU standard
              contractual clauses, or other approved safeguards under
              applicable GDPR provisions.
            </p>

            {/* Links to Other Websites */}
            <h2>Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are neither
              operated nor controlled in any way by us. If you click on a
              third-party link, you will be directed to that third
              party&apos;s site. We strongly advise you to review the Privacy
              Policy of every site you visit. We have no control over and
              assume no responsibility for the content, privacy policies, or
              practices of any third-party sites or services.
            </p>

            {/* Changes */}
            <h2>Changes to This Privacy Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will
              update the &quot;Last updated&quot; date at the top of this
              Privacy Policy to reflect the effective dates of the updates.
              You are advised to review this Privacy Policy periodically for
              any changes. Changes to this Privacy Policy are effective when
              they are posted on this page.
            </p>

            {/* Contact Us */}
            <h2>Contact Us</h2>
            <p>
              For matters related to data protection and privacy, you may
              contact our privacy team at{" "}
              <a href="mailto:privacy@ramsoft.com">privacy@ramsoft.com</a>.
            </p>
            <p>
              For matters relating to personal data protection under the GDPR
              or DPDPA, you may contact our Data Protection Officer at:{" "}
              <a href="mailto:dpo@ramsoft.com">dpo@ramsoft.com</a>
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
